name: wiki
base: core20 
version: '0.1'
summary: Simple CLI tool to fetch Wikipedia summaries
description: |
  This is a simple CLI tool that fetches and displays Wikipedia summaries.

grade: stable
confinement: strict

apps:
  wiki:
    command: bin/wiki
    plugs: network

parts:
  wiki:
    # See 'snapcraft plugins'
    plugin: python
    source: .
    requirements: ['requirements.txt']
